<?php 
require_once '../php/auth.php'; 
$name = $_SESSION['name'] ?? 'User'; // fallback to 'User'
$month = date('F Y'); // Example: July 2025
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Monthly Report | FinTrack Pro</title>
  <link rel="stylesheet" href="../css/dashboard_styles.css" />
  <link rel="stylesheet" href="../css/responsive_dashboard.css" />
  <link rel="stylesheet" href="../css/monthly_report.css" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" />
</head>
<body>
  <div class="main--content" >
    <h1>Monthly Financial Report</h1>
    <p><strong>Name:</strong> <?= htmlspecialchars($name) ?><br><strong>Month:</strong> <?= htmlspecialchars($month) ?></p>
    <hr>

    <h2 class="main--title">Overview Summary</h2>
    <table class="styled-table">
      <thead>
        <tr>
          <th>Metric</th>
          <th>Amount</th>
          <th>Change (%)</th>
        </tr>
      </thead>
      <tbody>
        <!-- Filled by JS -->
      </tbody>
    </table>

    <hr>

    <h2 class="main--title">Goal Progress</h2>
    <table class="goal-table styled-table">
      <thead>
        <tr>
          <th>Goal Type</th>
          <th>Target</th>
          <th>Actual</th>
          <th>Used / Achieved</th>
        </tr>
      </thead>
      <tbody>
        <!-- Filled by JS -->
      </tbody>
    </table>

    <hr>

    <div class="dual-column">
      <div>
        <h2 class="main--title">Expenses by Category</h2>
        <table class="styled-table">
          <thead>
            <tr><th>Category</th><th>Amount</th><th>Percent</th></tr>
          </thead>
          <tbody>
            <!-- Filled by JS -->
          </tbody>
        </table>
      </div>
      <div>
        <h2 class="main--title">Expenses by Payment Method</h2>
        <table class="styled-table">
          <thead>
            <tr><th>Method</th><th>Amount</th><th>Percent</th></tr>
          </thead>
          <tbody>
            <!-- Filled by JS -->
          </tbody>
        </table>
      </div>
    </div>

    <hr>

    <h2 class="main--title">Top 10 Expenses</h2>
    <table class="styled-table" id="top-transactions-table">
      <thead>
        <tr><th>Item</th><th>Amount</th></tr>
      </thead>
      <tbody>
        <!-- Filled by JS -->
      </tbody>
    </table>

    <hr>
    <p class="footer-text">Report generated by FinTrack Pro | © 2025</p>
  </div>

  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script>
    $(document).ready(function () {
      // Helper: Format percentage logic
      function getFormattedPercentage(value, isExpense = false) {
        const percent = parseFloat(value || 0).toFixed(2);
        const sign = value > 0 ? '+' : value < 0 ? '–' : '';
        const color = isExpense
          ? (value >= 0 ? '#ef5350' : '#2e7d32')
          : (value >= 0 ? '#2e7d32' : '#ef5350');
        const cssClass = value >= 0 ? 'positive' : 'negative';
        return { sign, percent, color, cssClass };
      }

      function getGoalColorClass(percent, type) {
        percent = parseFloat(percent);
        if (type === "expense") {
          if (percent > 70) return 'red';
          if (percent >= 45) return 'yellow';
          return 'green';
        } else if (type === "saving") {
          if (percent > 70) return 'green';
          if (percent >= 45) return 'yellow';
          return 'red';
        }
        return '';
      }

      // Overview Summary
      $.getJSON("../php/get_cards_data.php", function (data) {
        const incomeChange = getFormattedPercentage(data.percent_income);
        const expenseChange = getFormattedPercentage(data.percent_expense, true);
        const savingChange = getFormattedPercentage(data.percent_saving);

        $(".styled-table tbody").eq(0).html(`
          <tr>
            <td>Income</td>
            <td>₹${data.income.toLocaleString()}</td>
            <td class="${incomeChange.cssClass}" style="color:${incomeChange.color}">${incomeChange.sign}${Math.abs(incomeChange.percent)}%</td>
          </tr>
          <tr>
            <td>Expense</td>
            <td>₹${data.expense.toLocaleString()}</td>
            <td class="${expenseChange.cssClass}" style="color:${expenseChange.color}">${expenseChange.sign}${Math.abs(expenseChange.percent)}%</td>
          </tr>
          <tr>
            <td>Savings</td>
            <td>₹${data.saving.toLocaleString()}</td>
            <td class="${savingChange.cssClass}" style="color:${savingChange.color}">${savingChange.sign}${Math.abs(savingChange.percent)}%</td>
          </tr>
          <tr>
            <td>Debt</td>
            <td>₹0</td>
            <td class="negative" style="color:#2e7d32">0%</td>
          </tr>
        `);
      });

      // Goals Table with color
      $.when(
        $.getJSON("../php/get_goals_data.php"),
        $.getJSON("../php/get_cards_data.php")
      ).done(function (goalData, cardData) {
        const goals = goalData[0];
        const cards = cardData[0];

        const targetExpense = parseFloat(goals.target_expense) || 0;
        const targetSaving = parseFloat(goals.target_saving) || 0;
        const actualExpense = parseFloat(cards.expense) || 0;
        const actualSaving = parseFloat(cards.saving) || 0;

        let expensePercent = 0, savingPercent = 0;

        if (targetExpense > 0) expensePercent = ((actualExpense / targetExpense) * 100).toFixed(2);
        if (targetSaving > 0) savingPercent = ((actualSaving / targetSaving) * 100).toFixed(2);

        const expenseColorClass = getGoalColorClass(expensePercent, 'expense');
        const savingColorClass = getGoalColorClass(savingPercent, 'saving');

        $(".goal-table tbody").html(`
          <tr>
            <td>Expense</td>
            <td>₹${targetExpense.toLocaleString()}</td>
            <td>₹${actualExpense.toLocaleString()}</td>
            <td class="${expenseColorClass}">${expensePercent}% used</td>
          </tr>
          <tr>
            <td>Saving</td>
            <td>₹${targetSaving.toLocaleString()}</td>
            <td>₹${actualSaving.toLocaleString()}</td>
            <td class="${savingColorClass}">${savingPercent}% achieved</td>
          </tr>
        `);
      });

      // Category & Payment Method Tables
      $.getJSON("../php/get_graph_data.php", function (data) {
        const catLabels = data.monthly.expense.category.labels;
        const catAmounts = data.monthly.expense.category.data;
        const methodLabels = data.monthly.expense.method.labels;
        const methodAmounts = data.monthly.expense.method.data;

        const totalCategory = catAmounts.reduce((a, b) => a + b, 0);
        const totalMethod = methodAmounts.reduce((a, b) => a + b, 0);

        let catRows = "", methodRows = "";

        for (let i = 0; i < catLabels.length; i++) {
          const percent = ((catAmounts[i] / totalCategory) * 100).toFixed(2);
          catRows += `<tr><td>${catLabels[i]}</td><td>₹${catAmounts[i].toLocaleString()}</td><td>${percent}%</td></tr>`;
        }

        for (let i = 0; i < methodLabels.length; i++) {
          const percent = ((methodAmounts[i] / totalMethod) * 100).toFixed(2);
          methodRows += `<tr><td>${methodLabels[i]}</td><td>₹${methodAmounts[i].toLocaleString()}</td><td>${percent}%</td></tr>`;
        }

        $(".dual-column .styled-table tbody").eq(0).html(catRows);
        $(".dual-column .styled-table tbody").eq(1).html(methodRows);
      });

      // Top 10 Expenses
      $.getJSON('../php/get_top10_data.php', function (response) {
        if (response.top_transactions && response.top_transactions.length > 0) {
          const rows = response.top_transactions.map(tx => `
            <tr>
              <td>${tx.item}</td>
              <td>₹${parseFloat(tx.amount).toLocaleString()}</td>
            </tr>
          `).join('');
          $('#top-transactions-table tbody').html(rows);
        } else {
          $('#top-transactions-table tbody').html('<tr><td colspan="2">No transactions found.</td></tr>');
        }
      });
    });
  </script>
</body>
</html>
    